"use client";

/* eslint-disable @next/next/no-img-element */

import { ArrowRight, ArrowUpRight, BookOpen, ChevronLeft, ChevronRight, Clock3, Flame, Play } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { Formacao } from "../dados-comunidade";

export function InicioInterativo({ nome, formacoes }: { nome: string; formacoes: Formacao[] }) {
  const [slide, setSlide] = useState(0);
  const trilho = useRef<HTMLDivElement>(null);
  useEffect(() => { const card = trilho.current?.children[slide] as HTMLElement | undefined; card?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "start" }); }, [slide]);
  useEffect(() => { if (formacoes.length < 2) return; const timer = window.setInterval(() => setSlide((atual) => (atual + 1) % formacoes.length), 5500); return () => window.clearInterval(timer); }, [formacoes.length]);
  const mover = (direcao: number) => setSlide((atual) => (atual + direcao + formacoes.length) % formacoes.length);
  const destaque = formacoes[0];
  return <div className="content"><section className="welcome-row"><div><p className="kicker">ÁREA DE MEMBROS</p><h1>Continue evoluindo, {nome}.</h1><p>Conhecimento aplicado para liderar na nova economia.</p></div><div className="streak"><span><Flame size={22} /></span><div><strong>Comece hoje</strong><small>uma ação por vez</small></div></div></section>{destaque && <section className="continue-card"><div className="continue-art" aria-hidden="true"><img src={destaque.cover} alt="" /><div className="continue-art-shade" /><span className="art-label">{destaque.category} · FORMAÇÃO 01</span><span className="play-medallion"><Play size={24} fill="currentColor" /></span></div><div className="continue-info"><div><span className="status-label">COMECE POR UMA APLICAÇÃO REAL</span><h2>{destaque.title}</h2><p>{destaque.outcome} · {destaque.lessons} aulas</p></div><div className="continue-bottom"><div className="progress-wrap"><div className="progress-copy"><span>Direção recomendada</span><strong>{destaque.level}</strong></div><div className="progress"><i style={{ width: "18%" }} /></div></div><Link className="continue-link" href={`/formacoes/${destaque.slug}/aulas/1`}>Começar aula <ArrowRight size={18} /></Link></div></div></section>}
    <section className="tracks-section"><div className="section-heading"><div><p className="kicker">MÓDULOS INICIAIS</p><h2>Automações para aplicar no negócio</h2></div>{formacoes.length > 1 && <div className="carousel-controls"><span>{String(slide + 1).padStart(2, "0")} <i>/</i> {String(formacoes.length).padStart(2, "0")}</span><button onClick={() => mover(-1)} aria-label="Formação anterior"><ChevronLeft /></button><button onClick={() => mover(1)} aria-label="Próxima formação"><ChevronRight /></button></div>}</div><div className="carousel-window"><div className="track-carousel" ref={trilho}>{formacoes.map((formacao, index) => <article className="track-card" key={formacao.slug}><Link className="track-art" href={`/formacoes/${formacao.slug}`}><img src={formacao.cover} alt={`Capa da formação ${formacao.title}`} /><div className="track-overlay" /><span className="track-eyebrow">{formacao.category}</span><span className="track-number">{String(index + 1).padStart(2, "0")}</span></Link><div className="track-body"><h3>{formacao.title}</h3><p>{formacao.description}</p><span className="track-outcome">{formacao.outcome}</span><div className="track-meta"><span><BookOpen /> {formacao.lessons} aulas</span><span><Clock3 /> {formacao.duration}</span></div><Link className="start-track" href={`/formacoes/${formacao.slug}`}>Conhecer formação <ArrowUpRight /></Link></div></article>)}</div></div><div className="carousel-dots" aria-label="Selecionar formação">{formacoes.map((formacao, index) => <button key={formacao.slug} className={slide === index ? "active" : ""} onClick={() => setSlide(index)} aria-label={`Ir para ${formacao.title}`} />)}</div></section>
    <section className="audience-section audience-editorial"><div className="audience-intro"><p className="kicker">DIREÇÃO DE IMPLEMENTAÇÃO</p><h2>Aprenda.<br />Aplique. Meça.</h2><p>Escolha uma necessidade real, avance pelas aulas, use os materiais da biblioteca e registre a implementação em seus projetos.</p></div><div className="audience-cards">{[["01","Escolha um processo","Comece pelo gargalo que consome tempo ou perde receita."],["02","Implemente pequeno","Valide uma primeira versão antes de ampliar a automação."],["03","Registre o avanço","Use Meus projetos para acompanhar resultado e próxima ação."],["04","Compartilhe","Leve dúvidas e aprendizados para o feed da comunidade."]].map(([numero,titulo,texto]) => <article key={numero}><span>{numero}</span><div><strong>{titulo}</strong><p>{texto}</p></div></article>)}</div></section>
  </div>;
}
